version: '3'

services:
  # ngnix for port forwarding
  nginx:
    container_name: nginx-aires_api
    image: nginx:1.21.0
    restart: unless-stopped
    # For ENV in docker, see https://hub.docker.com/_/nginx
    env_file:
      - .env
    ports:
      - "${NGINX_HOST_PORT}:8443"
    volumes:
      # Template conf
      - ${NGINX_ROOT}/templates:/etc/nginx/templates/
      # SSL 
      - ${NGINX_ROOT}/ssl.conf:/config/nginx/ssl.conf:ro
      # Certificates
      - ${NGINX_CERT}:/etc/nginx/certs:ro
  # FLASK
  aires_flask_app:
    image: aires_flask_app_image
    container_name: aires_flask_app
    restart: always
    env_file:
      - .env
    build: 
      context: ${FLASK_ROOT_DIR}
      dockerfile: ${FLASK_ROOT_DIR}/flask.Dockerfile
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - ${PATH_TO_AIRES_MODELS}:${WORKDIR_PATH}/AIRES_MODELS/
  # FASTAPI
  aires_fastapi_app:
    image: aires_fastapi_app_image
    container_name: aires_fastapi_app
    restart: always
    env_file:
      - .env
    build: 
      context: ${FASTAPI_ROOT_DIR}
      dockerfile: ${FASTAPI_ROOT_DIR}/fastapi.Dockerfile
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    volumes:
      - ${PATH_TO_AIRES_MODELS}:${FASTAPI_WORKDIR_PATH}/AIRES_MODELS/

