version: '3'

services:
  aires_fastapi_app:
    image: aires_fastapi_app_image
    container_name: aires_fastapi_app
    restart: always
    env_file:
      - .env
    build: 
      context: ${FASTAPI_ROOT_DIR}
      dockerfile: ${FASTAPI_ROOT_DIR}/fastapi.Dockerfile
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    volumes:
      - ${PATH_TO_AIRES_MODELS}:${FASTAPI_WORKDIR_PATH}/AIRES_MODELS/